name: Get

on:
  schedule:
    - cron: '55 12 * * *'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Download
        uses: actions/checkout@v2
      -
        name: QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Push
        run: docker pull tmvdl/php -a
