name: Push

on:
  schedule:
    - cron: '30 15 * * 3' # Qua 12:30 - America/Sao_Paulo
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Download
        uses: actions/checkout@v2
      -
        name: QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: DockerHub
        uses: docker/login-action@v1 
        with:
          username: tmvdl
          password: ${{ secrets.GITHUBDOCKERPHP }}
      -
        name: Build
        run: sh build.sh 7.2 7.2-composer2 7.3 7.3-composer2
      -
        name: Push
        run: docker push tmvdl/php -a
